---
namespace: id-private-ghec-runner
resources:
  - ../base
configMapGenerator:
  - name: helm-values
    files:
      - helm-values.yaml
patches:
  - target:
      group: helm.toolkit.fluxcd.io 
      version: v2
      kind: HelmRelease
      name: arc-runner
    path: oci-namespace-patch.yaml
  - target:
      group: secrets-store.csi.x-k8s.io
      version: v1
      kind: SecretProviderClass
      name: azure-kvname-wi
    path: keyvault-patch.yaml
generatorOptions:
  disableNameSuffixHash: true