---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gha-runner-scale-set
spec:
  interval: 5m0s
  url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "^0.12.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runner
spec:
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
    namespace: template
  interval: 10m
  values:
    replicaCount: 2
