---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 706d9217-bc27-4786-9149-15627a279f1d
  name: workload-identity-sa
  namespace: default
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-wi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "706d9217-bc27-4786-9149-15627a279f1d"
    keyvaultName: kvunibeidghrunner6rwm
    cloudName: ""
    objects:  |
      array:
    tenantId: "d400387a-212f-43ea-ac7f-77aa12d7977e"
  secretObjects:
    - data:
