---
kind: Pod
apiVersion: v1
metadata:
  name: secretpod
spec:
  containers:
    - name: busybox
      image: busybox:1
      command:
      - "/bin/sleep"
      - "infinity"
      volumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kvname-wi"